<?php
/* Traductor: Alcyonecodigo (MABEDEEP)
 * 
 * Language File: Español
 *
 * Web del traductor: https://alcyonecodigo.es
 */

$lang = array();

$lang['banned']         = "Te han prohibido en " . $site_name;
$lang['expired']		= "La pasta que está buscando ha caducado.";
$lang['guestwelcome']	= $site_name . " Le permite enviar texto &amp; código.";
$lang['pleaseregister'] = "<br /><br /> <a class=\"btn btn-default\" data-target=\"#signin\" data-toggle=\"modal\" href=\"#\">Iniciar sesión</a> o <a class=\"btn btn-default\" data-target=\"#signup\" data-toggle=\"modal\" href=\"#\">Registro</a> para enviar una nueva pasta. Es gratis.";
$lang['registertoedit'] = "<a class=\"btn btn-default\" data-target=\"#signin\" data-toggle=\"modal\" href=\"#\">Iniciar sesión</a> o <a class=\"btn btn-default\" data-target=\"#signup\" data-toggle=\"modal\" href=\"#\">Registro</a> Para editar o clonar esta pasta. Es gratis.";
$lang['editpaste']		= "Editar";
$lang['forkpaste']		= "Clonar";
$lang['guestmsgtitle']	= $site_name . " Es para el código fuente y el texto de depuración general.";
$lang['guestmsgbody']	= "<a data-target=\"#signin\" data-toggle=\"modal\" href=\"#\">Iniciar sesión</a> o <a data-target=\"#signup\" data-toggle=\"modal\" href=\"#\">Registro</a> para editar, eliminar y mantener un seguimiento de sus pastas y mucho más.";
$lang['emptypastebin']	= "No hay pastas para mostrar.";
$lang['siteprivate']	= "Esta pasta es privada.Si el sitio esta en modo privado no se muestra nada aquí <br>y tampoco las ultimas pastas.";
$lang['image_wrong']    = "Captcha incorrecto.";
$lang['missing-input-response']   = "Falta el parámetro de respuesta reCAPTCHA. Verifique su configuración de PASTE.";
$lang['missing-input-secret']     = "Falta el parámetro secreto reCAPTCHA. Añádala a su configuración de PASTE.";
$lang['missing-input-response']   = "El parámetro de respuesta reCAPTCHA no es válido. Por favor, intenta completar de nuevo el reCAPTCHA.";
$lang['invalid-input-secret']     = "El parámetro secreto reCAPTCHA no es válido o está mal formado. Por favor revise su configuración de PASTE.";
$lang['empty_paste']	= "No puede publicar una pasta vacía.";
$lang['large_paste']	= "La pasta es demasiado grande. El tamaño máximo es " . $pastelimit . "MB";
$lang['paste_db_error'] = "No se puede publicar en la base de datos.";
$lang['error']          = "Algo salió mal.";
$lang['archive']        = "Archivo de Pastas";
$lang['contact']        = "Contáctenos";
$lang['full_name']      = "Su nombre completo es obligatorio.";
$lang['email']          = "Se requiere tu dirección de correo electrónico.";
$lang['email_invalid']  = "Tu dirección de correo electrónico parece no ser válida.";
$lang['message']        = "Su mensaje es obligatorio.";
$lang['login/register'] = "Inicio de sesión / Registro";
$lang['rememberme']		= "Manténgame conectado.";
$lang['mail_acc_con']   = "$site_name Confirmación de cuenta";
$lang['mail_suc']       = "El código de verificación se envió correctamente a su dirección de correo electrónico.";
$lang['email_ver']      = "Correo electrónico ya verificado.";
$lang['email_not']      = "Correo electrónico no encontrado.";
$lang['pass_change']    = "La contraseña ha cambiado correctamente y se ha enviado a su correo electrónico.";
$lang['notverified']	= "Cuenta no verificada.Las cuentas no verificadas se eliminan sin previo aviso...";
$lang['incorrect']		= "Usuario / contraseña incorrectos";
$lang['missingfields']	= "Todos los campos deben ser llenados.";
$lang['userexists']     = "Nombre de usuario ya tomado.";
$lang['emailexists']	= "Correo electrónico ya registrado.";
$lang['registered']		= "Su cuenta se ha registrado correctamente.";
$lang['usrinvalid']		= "Su nombre de usuario sólo puede contener letras o números.";
$lang['mypastes']		= "Mis pastas";
$lang['pastedeleted']	= "Pasta Eliminada.";
$lang['databaseerror']	= "No se puede publicar en la base de datos.";
$lang['userchanged']	= "El nombre de usuario ha cambiado correctamente.";
$lang['usernotvalid']	= "El nombre de usuario no es válido.";
$lang['privatepaste']	= "Esta es una pasta privada.";
$lang['wrongpassword']	= 'Contraseña incorrecta.';
$lang['pwdprotected']	= 'Pasta protegida por contraseña';
$lang['notfound']		= "Extraviado! , la url no existe";
$lang['wrongpwd']		= "Contraseña incorrecta. Inténtalo de nuevo.";
$lang['myprofile']		= "Mi perfil";
$lang['profileerror']	= "No se puede actualizar la información del perfil ";
$lang['profileupdated']	= "La información de tu perfil se actualiza ";
$lang['oldpasswrong']	= "Su contraseña antigua es incorrecta.";
$lang['archives']		= "Archivo de Pastas";
$lang['archivestitle']  = "Esta página contiene las 100 pastas públicas más recientemente creadas.";
$lang['pastetitle']		= "Título";
$lang['pastetime']		= "Tiempo";
$lang['pastesyntax']	= "Sintaxis";
$lang['pasteviews']		= "Visitas";
$lang['wentwrong']		= "Algo salió mal.";
$lang['versent']		= "Se ha enviado un correo de verificación a tu dirección de correo electrónico.";
$lang['modpaste']		= "Modificar Pasta";
$lang['newpaste']		= "Nueva Pasta";
$lang['highlighting']	= "Resaltado de sintaxis";
$lang['expiration']		= "Vencimiento";
$lang['visibility']		= "Visibilidad";
$lang['pwopt']			= "Contraseña (Opcional)";
$lang['encrypt']		= "Cifrar en la base de datos";
$lang['entercode']		= "Introduzca el código";
$lang['almostthere']	= "Casi allí. Un paso más para ir.";
$lang['username']		= "Nombre de usuario";
$lang['autogen']		= "Nombre generado automáticamente";
$lang['setuser']		= "Establecer su nombre de usuario";
$lang['keepuser']		= "Mantener el nombre generado automáticamente";
$lang['enterpwd']		= "Introduce la contraseña";
$lang['totalpastes']	= "Pastas totales:";
$lang['membtype']		= "Tipo de membresía:";
$lang['email']			= "Email";
$lang['fullname']		= "Nombre completo";
$lang['chgpwd']			= "Cambia la contraseña";
$lang['curpwd']			= "contraseña actual";
$lang['newpwd']			= "Nueva contraseña";
$lang['confpwd']		= "Confirmar contraseña";
$lang['mypastes']		= "Mis pastas";
$lang['viewpastes']		= "Ver todas mis pastas";
$lang['recentpastes']	= "Pastas recientes";
$lang['user_public_pastes'] = "'s Pastas";
$lang['yourpastes']		= "Tus Pastas";
$lang['mypastestitle']	= "Todas tus pastas, en un solo lugar.";
$lang['delete']			= "Borrar";
$lang['highlighted']	= "El texto de abajo está seleccionado, presione Ctrl + C para copiar en su portapapeles.";
$lang['newpaste']		= "Nueva Pasta";
$lang['download']		= "Descargar";
$lang['showlineno']		= "Mostrar / Ocultar línea no.";
$lang['copyto']			= "Copiar texto al portapapeles";
$lang['rawpaste']		= "Raw Pasta";
$lang['membersince']    = "Unido: ";
$lang['delete_error_invalid'] = "Error: Pasta no eliminada porque no existe o no posee la pasta.";
$lang['not_logged_in']  = "Error: debe iniciar sesión para hacer eso.";
$lang['public']         = "Público";
$lang['unlisted']       = "Sin listar (Unlisted)";
$lang['private']        = "Privado";
$lang['hello']			= "Hola";
$lang['profile-message'] = "Esta es su página de perfil donde puede administrar sus pastas. <br /> Todas sus pastas públicas, privadas y no listadas se mostrarán aquí. También puede eliminar sus pastas de esta página. Si otros usuarios visitan tu página, solo verán tus pastas públicas.";
$lang['profile-stats']	= "Algunas de sus estadísticas:";
$lang['profile-total-pastes'] = "Total de Pastas:";
$lang['profile-total-pub']	= "Total de pastas públicas:";
$lang['profile-total-unl']	= "Total de pastas no listadas:";
$lang['profile-total-pri']	= "Total de pastas privadas:";
$lang['profile-total-views'] = "Vistas totales de todas tus pastas:";
$lang['embed-hosted-by'] = "Alojado por";
$lang['view-raw']		= "Ver Raw";
?>
